[program:icbcrm-reverb]
process_name=%(program_name)s
command=php /home/icbcrm/artisan reverb:start
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/home/icbcrm/storage/logs/reverb.log
stopwaitsecs=3600
